#!/usr/bin/env python

# THIS FILE IS PART OF PyPad, AND IS GOVERENED BY A PERMISSIBILITY LICENSE 
# GOVERNING ITS USE AND DISTRIBUTION. YOU SHOULD HAVE RECIEVED A COPY OF THIS
# LICENSE WITH THE SOFTWARE; IF NOT PROVIDED, WRITE TO <tjlane@stanford.edu>.
#
# AUTHORS:
# TJ Lane <tjlane@stanford.edu>
# Jonas Sellberg <jonas.a.sellberg@stanford.edu>
#
# Apr 30, 2013

"""
A simple script that takes a CSPad specification and a raw image and renders
an assembled image.
"""

import tables
import argparse

from pypad import cspad
from pypad import utils
from pypad import read

import matplotlib.pyplot as plt
from pypad.plot import imshow_cspad

parser = argparse.ArgumentParser(description='''Use a CSPAD geometry to assemble a raw image.''')
                                 
parser.add_argument('image_file', help='The (raw) image file.')
parser.add_argument('--metrology', default=None, 
                    help='''A CSPAD Metrology. Either a flat text file of an 
                            optical metrology (see documentation) or a saved 
                            pypad.CSPad object. If not passed uses a default
                            metrology.''')
                            
args = parser.parse_args()

raw_image = read.load_raw_image(args.image_file)

if args.metrology:
    if args.metrology.endswith('.txt'):
        cs1 = cspad.CSPad(args.metrology)
    elif args.metrology.endswith('.cspad'):
        cs1 = cspad.CSPad.load(args.metrology)
    else:
        raise ValueError('Could not understand format of file: %s' % args.metrology)
else:
    cs1 = cspad.CSPad.default()

plt.figure()
imshow_cspad( cs1(raw_image) )
plt.show()
