#!/usr/bin/env python

"""
A simple script that takes a CSPad specification and a raw image and renders
an assembled image.
"""

import tables
import argparse

from pypad import cspad
from pypad import utils
from pypad import read

import matplotlib.pyplot as plt
from pypad.plot import imshow_cspad

parser = argparse.ArgumentParser(description='''Use a CSPAD geometry to assemble a raw image.''')
                                 
parser.add_argument('image_file', help='The (raw) image file.')
parser.add_argument('--metrology', default=None, 
                    help='''A CSPAD Metrology. Either a flat text file of an 
                            optical metrology (see documentation) or a saved 
                            pypad.CSPad object. If not passed uses a default
                            metrology.''')
                            
args = parser.parse_args()

raw_image = read.load_raw_image(args.image_file)

if args.metrology:
    cs1 = cspad.CSPad(args.metrology)
else:
    cs1 = cspad.CSPad.default()

plt.figure()
imshow_cspad( cs1(raw_image) )
plt.show()
