#!/usr/bin/env python

"""
Generate a mask for the CSPad, via an interactive environment.
"""

import argparse
import numpy as np

from pypad import read
from pypad import mask

# parse
parser = argparse.ArgumentParser(description='''Generate a mask for the CSPad,
                                             via an interactive environment.''')

parser.add_argument('image', help='''An image to display, to aid masking. 
                                     Consider using a dark calibration.''')                                     
parser.add_argument('--output', default='my_mask.mask',
                    help='''The name of the file to write, containing the final 
                            mask. Default: my_mask.mask''')
parser.add_argument('--format', default='pypad', choices=['pypad', 'odin', 'cheetah'],
                    help='''The file format to write.''')

args = parser.parse_args()

img = read.load_raw_image(args.image)
msk = mask.MaskGUI(img, filename=args.output, fmt=args.format)

