#!/usr/bin/env python

"""
Convert either a metrology or cspad object to Cheetah's x/y/z position files.
"""

import os
import argparse

from pypad import cspad

parser = argparse.ArgumentParser(description='''Convert either a set of psana 
parameters or a metrology (txt) file to Cheetah's geometry specification (h5 
file with x/y/z coordinate positions).''')
                                 
parser.add_argument('--metrology', default=None, 
                    help='''A CSPAD Metrology. Either a flat text file of an 
                            optical metrology (see documentation) or a saved 
                            pypad.CSPad object. If not passed uses a default
                            metrology.''')
parser.add_argument('--filename', help='Output cheetah filename (default: pixelmap-cheetah-raw.h5)', default='pixelmap-cheetah-raw.h5', required=False)
args = parser.parse_args()


if args.metrology:
    cs1 = cspad.CSPad(args.metrology)
else:
    cs1 = cspad.CSPad.default()
                     
cs1.to_cheetah(args.filename)


