#!/usr/bin/env python

"""
Convert either a metrology or cspad object to Cheetah's x/y/z position files.
"""

import os
import argparse

from pypad.autogeom import cspad

parser = argparse.ArgumentParser(description='''Convert either a set of psana 
parameters or a metrology (txt) file to Cheetah's geometry specification (h5 
files with x/y/z coordinate positions).''')
                                 
parser.add_argument('geometry', help='Metrology file or CSPad alignment parameter dir')
args = parser.parse_args()


if os.path.isdir(args.geometry):
    geom = cspad.CSPad.from_dir(args.geometry)
    
elif args.geometry.endswith('.txt'):
    geom = cspad.Metrology(args.geometry)
    
else:
    raise ValueError('Cannot understand: %s, is not a parameter dir or metrology'
                     ' file' % args.geometry)
                     
geom.to_cheetah()



