#!/usr/bin/env python

"""
Score an optimized geometry by testing it on a reference sample.

ToDo
----
Extract energy/path length from psana directly...
"""

import argparse
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.patches as plt_patches

from pypad import cspad
from pypad import utils
from pypad import read
from pypad.autogeom import score


# parse
parser = argparse.ArgumentParser(description='''Score an optimized geometry by
                                           testing it on a reference sample.''')

parser.add_argument('params', help='A score_params yaml file.')
# parser.add_argument('--energy', type=float, default=9600,
#                     help='A guess for photon energy of the x-ray beam [eV]. '
#                           'Default: 9600 eV.')
# parser.add_argument('--offset', type=float, default=0.0,
#                     help='A guess for distance offest from the sample to the '
#                          'detector [mm]. Default: 0.0 mm.u')


args = parser.parse_args()


print "\n\t--- SCOREING CSPAD GEOMETRY ---\t\n"
print " Figure Explanation:"
print " Left Panel:  The assembled image, superimposed with white circles where"
print "              theoretically there should be powder rings."
print " Right Panel: The radial projection for each individual quad, dotted"
print "              lines are theoretical peak predictions."
print
print "To plot additional samples"
print "   Press: l for previous sample"
print "   Press: n for next sample"
print
print

sref = score.PowderReference.load( args.params )
sref.evaluate()
sref.display()





