#!/usr/bin/env python

# THIS FILE IS PART OF PyPad, AND IS GOVERENED BY A PERMISSIBILITY LICENSE 
# GOVERNING ITS USE AND DISTRIBUTION. YOU SHOULD HAVE RECIEVED A COPY OF THIS
# LICENSE WITH THE SOFTWARE; IF NOT PROVIDED, WRITE TO <tjlane@stanford.edu>.
#
# AUTHORS:
# TJ Lane <tjlane@stanford.edu>
# Jonas Sellberg <jonas.a.sellberg@gmail.com>
#
# Apr 30, 2013

"""
Sketch a CSPad metrology. Useful for debugging.
"""

import argparse
from pypad import cspad
from pypad.plot import sketch_2x1s

parser = argparse.ArgumentParser(description='''Sketch a CSPad metrology. 
Useful for debugging.''')

parser.add_argument('-m', '--metrology', help='''A CSPAD Metrology. Note you can also pass
"default" to draw a default CSPad, which is useful to show you how things 
should look.''', default='default')
parser.add_argument('-t', '--type', help='''The metrology type.''', 
                    default='cxi', choices=['cxi', 'xpp'])
                            
args = parser.parse_args()

if args.metrology == 'default':
    cs1 = cspad.CSPad.default()
else:
    if args.type == 'cxi':
        cs1 = cspad.CSPad.load(args.metrology)
        if type(args.metrology) == str:
            cs1.dilate(5.0)
    elif args.type == 'xpp':
        cs1 = cspad.XppCSPad.load(args.metrology)

sketch_2x1s(cs1.pixel_positions)

